[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
pont_network = "ApvfQGqW8kzLyiG8x8PTrWJS7o2uLxXNjns6bYLh3H1R"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
