[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
pont_network = "3dnBfuMPHW52smosEsJwsnLGCR56DrphyUG68GqAcVxb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/pont_network.ts"
